// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	kv.proto

It has these top-level messages:
	InsertRequest
	InsertResponse
	LookupRequest
	LookupResponse
	KeysRequest
	KeysResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type InsertRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *InsertRequest) Reset()                    { *m = InsertRequest{} }
func (m *InsertRequest) String() string            { return proto1.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()               {}
func (*InsertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InsertRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InsertRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InsertResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *InsertResponse) Reset()                    { *m = InsertResponse{} }
func (m *InsertResponse) String() string            { return proto1.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()               {}
func (*InsertResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InsertResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LookupRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *LookupRequest) Reset()                    { *m = LookupRequest{} }
func (m *LookupRequest) String() string            { return proto1.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()               {}
func (*LookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LookupRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LookupResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *LookupResponse) Reset()                    { *m = LookupResponse{} }
func (m *LookupResponse) String() string            { return proto1.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()               {}
func (*LookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LookupResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeysRequest struct {
}

func (m *KeysRequest) Reset()                    { *m = KeysRequest{} }
func (m *KeysRequest) String() string            { return proto1.CompactTextString(m) }
func (*KeysRequest) ProtoMessage()               {}
func (*KeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type KeysResponse struct {
	Keys []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *KeysResponse) Reset()                    { *m = KeysResponse{} }
func (m *KeysResponse) String() string            { return proto1.CompactTextString(m) }
func (*KeysResponse) ProtoMessage()               {}
func (*KeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto1.RegisterType((*InsertRequest)(nil), "proto.InsertRequest")
	proto1.RegisterType((*InsertResponse)(nil), "proto.InsertResponse")
	proto1.RegisterType((*LookupRequest)(nil), "proto.LookupRequest")
	proto1.RegisterType((*LookupResponse)(nil), "proto.LookupResponse")
	proto1.RegisterType((*KeysRequest)(nil), "proto.KeysRequest")
	proto1.RegisterType((*KeysResponse)(nil), "proto.KeysResponse")
}

func init() { proto1.RegisterFile("kv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x1b, 0xfb, 0x61, 0x3b, 0x9a, 0x2a, 0x63, 0x95, 0xd0, 0x93, 0xce, 0x41, 0x8a, 0x87,
	0x46, 0x23, 0xd2, 0xbb, 0x37, 0xa9, 0xa7, 0x08, 0x1e, 0xbc, 0xa5, 0x71, 0x10, 0x49, 0xe9, 0xc6,
	0x4c, 0x12, 0xc8, 0x1f, 0xf3, 0xf7, 0xc9, 0xee, 0x26, 0xa1, 0x11, 0x7a, 0x9a, 0x0f, 0xe6, 0x99,
	0x79, 0xdf, 0x81, 0x71, 0x52, 0x2e, 0xd3, 0x4c, 0xe5, 0x0a, 0x87, 0x26, 0xd0, 0x0a, 0xdc, 0x97,
	0x9d, 0x70, 0x96, 0x87, 0xfc, 0x53, 0xb0, 0xe4, 0x78, 0x0e, 0xfd, 0x84, 0x2b, 0xcf, 0xb9, 0x76,
	0x16, 0x93, 0x50, 0xa7, 0x38, 0x83, 0x61, 0x19, 0x6d, 0x0b, 0xf6, 0x8e, 0x4c, 0xcf, 0x16, 0x74,
	0x07, 0xd3, 0x06, 0x94, 0x54, 0xed, 0x84, 0xd1, 0x83, 0x63, 0x29, 0xe2, 0x98, 0x45, 0x0c, 0x3d,
	0x0e, 0x9b, 0x92, 0x6e, 0xc0, 0x7d, 0x55, 0x2a, 0x29, 0xd2, 0x83, 0x47, 0xe8, 0x16, 0xa6, 0xcd,
	0x48, 0xbd, 0xae, 0x3d, 0xeb, 0xec, 0x9f, 0x75, 0xe1, 0x64, 0xcd, 0x95, 0xd4, 0x8b, 0x88, 0xe0,
	0xd4, 0x96, 0x35, 0x84, 0x30, 0x48, 0xb8, 0xd2, 0x02, 0xfa, 0x8b, 0x49, 0x68, 0xf2, 0xe0, 0xd7,
	0x81, 0xb3, 0x35, 0x57, 0xef, 0x9a, 0x7f, 0xe3, 0xac, 0xfc, 0x8e, 0x19, 0x57, 0x30, 0xb2, 0xea,
	0x71, 0x66, 0xff, 0xb1, 0xec, 0x7c, 0x61, 0x7e, 0xf9, 0xaf, 0x6b, 0xd7, 0x53, 0x4f, 0x83, 0x56,
	0x67, 0x0b, 0x76, 0x9c, 0xb5, 0x60, 0xd7, 0x0c, 0xf5, 0xf0, 0x01, 0x06, 0x5a, 0x29, 0x62, 0x3d,
	0xb0, 0xe7, 0x62, 0x7e, 0xd1, 0xe9, 0x35, 0xc8, 0xb3, 0xf7, 0x71, 0xf5, 0x19, 0xe5, 0x4f, 0xc1,
	0xbd, 0xbf, 0x8d, 0x36, 0x81, 0xff, 0x95, 0xa5, 0xb1, 0x6f, 0x06, 0x37, 0x23, 0x13, 0x1e, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0x5f, 0x14, 0x13, 0xcf, 0x01, 0x00, 0x00,
}
